"""Word document generation utilities."""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path
from typing import Sequence

from docx import Document
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT, WD_LINE_SPACING
from docx.shared import Pt, Inches, RGBColor
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

LOGGER = logging.getLogger(__name__)


class DocumentGenerator:
    """Generate patient narrative Word documents."""

    def __init__(self) -> None:
        LOGGER.debug("DocumentGenerator initialized")

    def create_narrative_document(
        self,
        narrative_text: str,
        subject_id: str,
        sequence_number: int,
        output_path: Path | str,
    ) -> Path:
        """Create narrative in green table format per narrative guide."""
        doc = Document()
        self._apply_styles(doc)
        
        # Set document margins
        sections = doc.sections
        for section in sections:
            section.top_margin = Inches(1)
            section.bottom_margin = Inches(1)
            section.left_margin = Inches(1)
            section.right_margin = Inches(1)
        
        doc.core_properties.title = "Patient Safety Narrative"
        doc.core_properties.comments = "Generated by Patient Narrative Automation POC"

        # ==================== HEADER SECTION ====================
        
        # Title
        title = doc.add_paragraph()
        title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        title_run = title.add_run("Patient Safety Narrative")
        title_run.font.size = Pt(16)
        title_run.font.bold = True
        title_run.font.color.rgb = RGBColor(0, 51, 102)  # Dark blue
        
        doc.add_paragraph()  # Blank line

        # Subtitle
        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        subtitle_run = subtitle.add_run(f"Subject {subject_id}, AE Sequence {sequence_number}")
        subtitle_run.font.size = Pt(12)
        subtitle_run.font.bold = True
        
        doc.add_paragraph()  # Blank line

        # Horizontal line
        separator = doc.add_paragraph()
        separator.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        sep_run = separator.add_run("_" * 80)
        sep_run.font.size = Pt(10)
        sep_run.font.color.rgb = RGBColor(128, 128, 128)  # Gray
        
        doc.add_paragraph()  # Blank line

        # ==================== TABLE SECTION ====================
        
        # Parse narrative into sections
        paragraphs = [p.strip() for p in narrative_text.split("\n\n") if p.strip()]
        
        # Create table (2 columns)
        table = doc.add_table(rows=1, cols=2)
        table.style = 'Table Grid'
        
        # Set column widths
        for row in table.rows:
            row.cells[0].width = Inches(2.5)  # Section name column
            row.cells[1].width = Inches(5.0)  # Content column
        
        # HEADER ROW
        header_cells = table.rows[0].cells
        header_cells[0].text = "Narrative Section"
        header_cells[1].text = "Content"
        
        # Format header cells with green background
        for cell in header_cells:
            # Set light green background
            shading = OxmlElement('w:shd')
            shading.set(qn('w:fill'), 'E2EFD9')  # Light green
            cell._element.get_or_add_tcPr().append(shading)
            
            # Make text bold
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True
                    run.font.size = Pt(11)
        
        # DATA ROWS - Map paragraphs to sections
        section_names = [
            "Paragraph 1: Demographics & Medical History",
            "Paragraph 2: Concomitant Medications",
            "Paragraph 3: Study Drug Dosing",
            "Event Description",
            "Drug Action & Assessment"
        ]
        
        for idx, (section_name, content) in enumerate(zip(section_names, paragraphs)):
            if content:  # Only add if content exists
                row_cells = table.add_row().cells
                
                # Section name (left column) - BOLD
                section_para = row_cells[0].paragraphs[0]
                section_run = section_para.add_run(section_name)
                section_run.font.bold = True
                section_run.font.size = Pt(11)
                
                # Content (right column) - REGULAR
                content_para = row_cells[1].paragraphs[0]
                content_run = content_para.add_run(content)
                content_run.font.size = Pt(11)
                content_para.alignment = WD_PARAGRAPH_ALIGNMENT.JUSTIFY

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        doc.save(output_path)
        LOGGER.info("Narrative document saved to %s (green table format)", output_path)
        return output_path

    def create_batch_document(
        self,
        narratives_list: Sequence[dict],
        output_path: Path | str,
    ) -> Path:
        doc = Document()
        self._apply_styles(doc)
        doc.core_properties.title = "Patient Safety Narratives - Batch Report"
        doc.add_heading("Patient Safety Narratives - Batch Report", level=1)
        doc.add_paragraph(f"Generated on {datetime.utcnow().strftime('%d-%b-%Y %H:%M UTC')}")

        for narrative in narratives_list:
            doc.add_page_break()
            subject_id = narrative["subject_id"]
            sequence_number = narrative["sequence_number"]
            text = narrative["narrative_text"]
            self._append_narrative(doc, text, subject_id, sequence_number)

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        doc.save(output_path)
        LOGGER.info("Batch narrative document saved to %s", output_path)
        return output_path

    @staticmethod
    def _apply_styles(doc: Document) -> None:
        """Apply professional document styles."""
        style = doc.styles["Normal"]
        font = style.font
        font.name = "Calibri"
        font.size = Pt(11)
        
        # Set paragraph formatting for Normal style
        para_format = style.paragraph_format
        para_format.space_after = Pt(14)
        para_format.line_spacing = 1.15

    def _append_narrative(
        self,
        doc: Document,
        narrative_text: str,
        subject_id: str,
        sequence_number: int,
    ) -> None:
        """Append a narrative to batch document with formatting."""
        heading = doc.add_heading(f"Subject {subject_id} - AE Sequence {sequence_number}", level=2)
        heading_run = heading.runs[0]
        heading_run.font.color.rgb = RGBColor(0, 51, 102)
        
        for paragraph in filter(None, [p.strip() for p in narrative_text.split("\n\n")]):
            para = doc.add_paragraph(paragraph, style="Normal")
            para_format = para.paragraph_format
            para_format.space_after = Pt(14)
            para_format.line_spacing = 1.15
            para.alignment = WD_PARAGRAPH_ALIGNMENT.JUSTIFY

